"""Manage the CGP auto-patcher VS Code workspace extension."""

from __future__ import annotations

import glob
import json
import os
import shutil
import sys
import textwrap
import time
from pathlib import Path
from typing import Optional

from . import __version__
from .discovery import _is_wsl, _ordered_wsl_user_dirs, _wsl_user_dirs

EXTENSION_NAME = "cgp-auto-patcher"
EXTENSION_ID = f"cgp.{EXTENSION_NAME}"
GITHUB_REPO = "baaaaaaaka/cursor_gui_patch"
RELOAD_MODES = {"prompt", "auto", "off"}
DEFAULT_RELOAD_MODE = "prompt"
DEFAULT_RELOAD_DELAY_MS = 1200


def _wsl_gui_extensions_root() -> Optional[Path]:
    """Find the Windows Cursor extensions directory from within WSL."""
    users_dir = Path("/mnt/c/Users")
    if not users_dir.is_dir():
        return None

    for user_dir in _ordered_wsl_user_dirs(_wsl_user_dirs(users_dir)):
        ext_dir = user_dir / ".cursor" / "extensions"
        if ext_dir.is_dir():
            return ext_dir
    return None


def _extensions_root(target: str) -> Path:
    """Return the Cursor extensions root directory for *target* ('gui' or 'server')."""
    if target == "server":
        return Path.home() / ".cursor-server" / "extensions"
    # gui (default)
    if sys.platform == "darwin":
        return Path.home() / ".cursor" / "extensions"
    if sys.platform == "win32":
        return Path(os.environ.get("USERPROFILE", "~")) / ".cursor" / "extensions"
    # Linux — check for WSL (Windows Cursor reads from Windows filesystem)
    if _is_wsl():
        wsl_root = _wsl_gui_extensions_root()
        if wsl_root:
            return wsl_root
    return Path.home() / ".cursor" / "extensions"


def _ext_dir_name(version: str) -> str:
    return f"{EXTENSION_NAME}-{version}"


def _find_existing(extensions_root: Path) -> list[Path]:
    """Find all existing cgp-auto-patcher-* directories under *extensions_root*."""
    pattern = str(extensions_root / f"{EXTENSION_NAME}-*")
    return sorted(Path(p) for p in glob.glob(pattern) if Path(p).is_dir())


def _normalize_reload_mode(reload_mode: str) -> str:
    mode = (reload_mode or "").strip().lower()
    if mode not in RELOAD_MODES:
        allowed = ", ".join(sorted(RELOAD_MODES))
        raise ValueError(f"Invalid reload mode: {reload_mode!r}. Expected one of: {allowed}")
    return mode


def _normalize_reload_delay_ms(reload_delay_ms: int) -> int:
    value = int(reload_delay_ms)
    if value < 0:
        raise ValueError("reload_delay_ms must be >= 0")
    return value


def _generate_package_json(
    version: str,
    *,
    reload_mode: str = DEFAULT_RELOAD_MODE,
    reload_delay_ms: int = DEFAULT_RELOAD_DELAY_MS,
) -> str:
    mode = _normalize_reload_mode(reload_mode)
    delay_ms = _normalize_reload_delay_ms(reload_delay_ms)
    return json.dumps(
        {
            "name": EXTENSION_NAME,
            "displayName": "CGP Auto Patcher",
            "description": "Auto re-apply cursor-gui-patch after Cursor updates",
            "version": version,
            "publisher": "cgp",
            "engines": {"vscode": "^1.80.0"},
            "extensionKind": ["workspace"],
            "activationEvents": ["onStartupFinished"],
            "main": "./extension.js",
            "contributes": {
                "configuration": {
                    "title": "CGP Auto Patcher",
                    "properties": {
                        "cgp.autoPatcher.reloadMode": {
                            "type": "string",
                            "enum": ["prompt", "auto", "off"],
                            "default": mode,
                            "description": (
                                "Relaunch behavior after cgp patches files. "
                                "prompt=ask, auto=relaunch automatically, off=never relaunch."
                            ),
                        },
                        "cgp.autoPatcher.reloadDelayMs": {
                            "type": "integer",
                            "minimum": 0,
                            "default": delay_ms,
                            "description": "Delay before auto relaunch (milliseconds).",
                        },
                    },
                },
            },
        },
        indent=2,
    )


def _generate_extension_js() -> str:
    return textwrap.dedent("""\
        // CGP Auto Patcher – generated by cursor-gui-patch
        // This extension ensures cgp is available and runs `cgp patch` on activation.
        const vscode = require('vscode');
        const { execFile, exec } = require('child_process');
        const https = require('https');
        const fs = require('fs');
        const path = require('path');
        const os = require('os');

        const REPO = '""" + GITHUB_REPO + """';
        const DOWNLOAD_FAILS_BEFORE_CACHE = 2;
        const MAX_CACHED_ASSETS = 3;

        // ── activate ──────────────────────────────────────
        async function activate(context) {
            try {
                const cgp = await ensureCgp();
                if (cgp) await runPatch(cgp);
            } catch (_) { /* never throw into Cursor */ }
        }

        // ── ensureCgp ─────────────────────────────────────
        async function ensureCgp() {
            // 1. Check PATH
            const found = await which('cgp');
            if (found) return found;

            const paths = getInstallPaths();
            if (fs.existsSync(paths.knownBin)) return paths.knownBin;

            const state = readDownloadState(paths);
            let failures = toInt(state.consecutiveFailures, 0);

            try {
                const installed = await downloadLatest(paths);
                if (installed) {
                    writeDownloadState(paths, {
                        consecutiveFailures: 0,
                        lastSource: 'network',
                        updatedAt: Date.now(),
                    });
                    return installed;
                }
            } catch (_) {
                // Ignore network/download errors and continue to cache fallback path.
            }

            failures += 1;
            writeDownloadState(paths, {
                consecutiveFailures: failures,
                lastSource: 'network_failed',
                updatedAt: Date.now(),
            });

            if (failures >= DOWNLOAD_FAILS_BEFORE_CACHE) {
                const cached = await installFromCache(paths);
                if (cached) {
                    writeDownloadState(paths, {
                        consecutiveFailures: 0,
                        lastSource: 'cache',
                        updatedAt: Date.now(),
                    });
                    return cached;
                }
            }

            return null;
        }

        // ── downloadLatest ────────────────────────────────
        async function downloadLatest(paths) {
            const apiUrl = `https://api.github.com/repos/${REPO}/releases/latest`;
            const releaseJson = await httpsGet(apiUrl);
            const release = JSON.parse(releaseJson.toString('utf8'));
            const tag = release.tag_name;
            if (!tag) return null;

            const assetName = selectAsset(process.platform, process.arch);
            if (!assetName) return null;

            const downloadUrl = `https://github.com/${REPO}/releases/download/${tag}/${assetName}`;
            const data = await httpsGet(downloadUrl);
            fs.mkdirSync(paths.cacheDir, { recursive: true });

            const cacheName = `${sanitizeTag(tag)}--${assetName}`;
            const cachePath = path.join(paths.cacheDir, cacheName);
            fs.writeFileSync(cachePath, data);
            pruneCache(paths.cacheDir);

            return await installFromArchive(cachePath, assetName, tag, paths);
        }

        async function installFromCache(paths) {
            const expectedAsset = selectAsset(process.platform, process.arch);
            if (!expectedAsset) return null;

            let names = [];
            try {
                names = fs.readdirSync(paths.cacheDir);
            } catch (_) {
                return null;
            }

            const candidates = names
                .map((name) => {
                    const parsed = parseCachedName(name);
                    if (!parsed) return null;
                    if (parsed.assetName !== expectedAsset) return null;
                    const full = path.join(paths.cacheDir, name);
                    let stat = null;
                    try { stat = fs.statSync(full); } catch (_) {}
                    if (!stat || !stat.isFile()) return null;
                    return {
                        full,
                        mtimeMs: toInt(stat.mtimeMs, 0),
                        assetName: parsed.assetName,
                        tag: parsed.tag,
                    };
                })
                .filter(Boolean)
                .sort((a, b) => b.mtimeMs - a.mtimeMs);

            for (const item of candidates) {
                try {
                    const installed = await installFromArchive(item.full, item.assetName, item.tag, paths);
                    if (installed) return installed;
                } catch (_) {
                    // Try next cached archive.
                }
            }
            return null;
        }

        function parseCachedName(name) {
            if (!(name.endsWith('.tar.gz') || name.endsWith('.zip'))) return null;
            const idx = name.indexOf('--');
            if (idx <= 0) return null;
            const tag = name.slice(0, idx);
            const assetName = name.slice(idx + 2);
            if (!assetName) return null;
            return { tag, assetName };
        }

        async function installFromArchive(archivePath, assetName, tag, paths) {
            const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'cgp-'));

            try {
                const localArchive = path.join(tmpDir, assetName);
                fs.copyFileSync(archivePath, localArchive);

                // Extract
                if (assetName.endsWith('.tar.gz')) {
                    await execPromise(`tar xzf "${localArchive}"`, { cwd: tmpDir });
                } else if (assetName.endsWith('.zip')) {
                    if (process.platform === 'win32') {
                        const psArchive = localArchive.replace(/'/g, "''");
                        const psTmpDir = tmpDir.replace(/'/g, "''");
                        await execPromise(
                            `powershell -NoProfile -Command "Expand-Archive -Path '${psArchive}' -DestinationPath '${psTmpDir}' -Force"`,
                            { cwd: tmpDir }
                        );
                    } else {
                        await execPromise(`unzip -o "${localArchive}"`, { cwd: tmpDir });
                    }
                } else {
                    return null;
                }

                return installExtractedBundle(tmpDir, tag, paths);
            } finally {
                try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch (_) {}
            }
        }

        function installExtractedBundle(tmpDir, tag, paths) {
            const versionTag = sanitizeTag(tag) || `cached-${Date.now()}`;
            const versionDir = path.join(paths.versionsDir, versionTag);

            fs.mkdirSync(paths.versionsDir, { recursive: true });
            fs.mkdirSync(paths.binDir, { recursive: true });

            if (fs.existsSync(versionDir)) {
                fs.rmSync(versionDir, { recursive: true, force: true });
            }

            const extractedCgp = path.join(tmpDir, 'cgp');
            if (!fs.existsSync(extractedCgp)) return null;
            fs.renameSync(extractedCgp, versionDir);

            const exePath = path.join(versionDir, paths.exeName);
            let exeOk = false;
            try { exeOk = fs.existsSync(exePath) && fs.statSync(exePath).isFile(); } catch (_) {}
            if (!exeOk) return null;

            if (process.platform !== 'win32') {
                try { fs.chmodSync(exePath, 0o755); } catch (_) {}
            }

            if (process.platform === 'win32') {
                // Windows users often cannot create symlinks without admin/dev mode.
                // Use copy fallback so installation is still usable.
                try { fs.rmSync(paths.currentLink, { recursive: true, force: true }); } catch (_) {}
                try { fs.cpSync(versionDir, paths.currentLink, { recursive: true }); } catch (_) {}
                const currentExe = path.join(paths.currentLink, paths.exeName);
                try { fs.copyFileSync(currentExe, paths.knownBin); } catch (_) {}
                let binOk = false;
                try { binOk = fs.existsSync(paths.knownBin) && fs.statSync(paths.knownBin).isFile(); } catch (_) {}
                return binOk ? paths.knownBin : currentExe;
            }

            // Unix: prefer symlinks for fast upgrades.
            try { fs.unlinkSync(paths.currentLink); } catch (_) {}
            try { fs.symlinkSync(versionDir, paths.currentLink); } catch (_) {}
            try { fs.unlinkSync(paths.knownBin); } catch (_) {}
            try { fs.symlinkSync(exePath, paths.knownBin); } catch (_) {}
            return paths.knownBin;
        }

        // ── runPatch ──────────────────────────────────────
        async function runPatch(cgpPath) {
            return new Promise((resolve) => {
                execFile(cgpPath, ['patch'], { timeout: 60000 }, (err, stdout, stderr) => {
                    if (err) { resolve(); return; }
                    const output = (stdout || '').toString();
                    const m = output.match(/Patched:\\s*(\\d+)/i);
                    const patchedCount = m ? parseInt(m[1], 10) : 0;
                    if (patchedCount > 0) {
                        handleReloadAfterPatch(patchedCount).finally(() => resolve());
                        return;
                    }
                    resolve();
                });
            });
        }

        async function handleReloadAfterPatch(patchedCount) {
            const cfg = getReloadConfig();
            const hasDirty = hasDirtyEditors();
            if (isRemoteWindow()) {
                await handleRemoteRefreshAfterPatch(patchedCount, cfg, hasDirty);
                return;
            }
            await handleLocalRefreshAfterPatch(patchedCount, cfg, hasDirty);
        }

        async function handleLocalRefreshAfterPatch(patchedCount, cfg, hasDirty) {
            if (cfg.mode === 'auto' && !hasDirty) {
                vscode.window.showInformationMessage(
                    `CGP: Patched ${patchedCount} file(s). Relaunching Cursor...`
                );
                await relaunchCursorApp(cfg.delayMs);
                return;
            }

            if (cfg.mode === 'off') {
                vscode.window.showWarningMessage(
                    `CGP: Patched ${patchedCount} file(s). Fully relaunch Cursor before opening new windows.`
                );
                return;
            }

            // Prompt mode, or auto mode fallback when there are unsaved files.
            const msg = hasDirty && cfg.mode === 'auto'
                ? `CGP: Patched ${patchedCount} file(s). Unsaved files detected. Save them, then relaunch Cursor to refresh all windows.`
                : `CGP: Patched ${patchedCount} file(s). Relaunch Cursor to refresh all windows.`;
            const choice = await vscode.window.showWarningMessage(
                msg,
                { modal: true },
                'Relaunch Cursor',
                'Later'
            );
            if (choice === 'Relaunch Cursor') {
                await relaunchCursorApp(cfg.delayMs);
            }
        }

        async function handleRemoteRefreshAfterPatch(patchedCount, cfg, hasDirty) {
            if (cfg.mode === 'auto' && !hasDirty) {
                vscode.window.showInformationMessage(
                    `CGP: Patched ${patchedCount} file(s). Reloading this window...`
                );
                await fallbackReloadWindow();
                return;
            }

            if (cfg.mode === 'off') {
                vscode.window.showWarningMessage(
                    `CGP: Patched ${patchedCount} file(s). Reload this window or reconnect later to refresh the remote server.`
                );
                return;
            }

            const msg = hasDirty && cfg.mode === 'auto'
                ? `CGP: Patched ${patchedCount} file(s). Unsaved files detected. Save them, then reload this window to refresh the remote server.`
                : `CGP: Patched ${patchedCount} file(s). Reload this window to refresh the remote server.`;
            const choice = await vscode.window.showWarningMessage(
                msg,
                { modal: true },
                'Reload Window',
                'Later'
            );
            if (choice === 'Reload Window') {
                await fallbackReloadWindow();
            }
        }

        async function relaunchCursorApp(delayMs) {
            if (!canRelaunchCursorApp()) {
                await fallbackReloadWindow();
                return;
            }

            const scheduled = scheduleCursorRelaunch(delayMs);
            if (!scheduled) {
                await fallbackReloadWindow();
                return;
            }

            try {
                await vscode.commands.executeCommand('workbench.action.quit');
            } catch (_) {
                await fallbackReloadWindow();
            }
        }

        function canRelaunchCursorApp() {
            return !isRemoteWindow() && !!getCursorExecPath();
        }

        function isRemoteWindow() {
            try {
                return !!(vscode.env && vscode.env.remoteName);
            } catch (_) {
                return false;
            }
        }

        function getCursorExecPath() {
            if (isRemoteWindow()) return '';
            const appPath = process.execPath;
            return typeof appPath === 'string' && appPath ? appPath : '';
        }

        async function fallbackReloadWindow() {
            try {
                await vscode.commands.executeCommand('workbench.action.reloadWindow');
            } catch (_) {}
        }

        function scheduleCursorRelaunch(delayMs) {
            const appPath = getCursorExecPath();
            if (!appPath) return false;
            const currentPid = toInt(process.pid, 0);
            if (currentPid <= 0) return false;

            const delaySecs = Math.max(1, Math.ceil(Math.max(0, delayMs) / 1000));
            const waitTimeoutSecs = Math.max(delaySecs + 30, 180);

            try {
                let child;
                if (process.platform === 'win32') {
                    const comspec = process.env.COMSPEC || 'cmd.exe';
                    const escapedApp = String(appPath).replace(/"/g, '""');
                    const script = `for /L %i in (1,1,${waitTimeoutSecs}) do @(tasklist /FI "PID eq ${currentPid}" 2>nul | find "${currentPid}" >nul && (ping 127.0.0.1 -n 2 >nul) || (ping 127.0.0.1 -n ${delaySecs + 1} >nul && start "" "${escapedApp}" & exit))`;
                    child = execFile(comspec, ['/d', '/s', '/c', script], {
                        detached: true,
                        stdio: 'ignore',
                        windowsHide: true,
                    });
                } else {
                    const script = `i=0; while [ "$i" -lt ${waitTimeoutSecs} ]; do if ! kill -0 ${currentPid} 2>/dev/null; then sleep ${delaySecs}; ${quoteForShell(appPath)} >/dev/null 2>&1 & exit 0; fi; i=$((i+1)); sleep 1; done; exit 0`;
                    child = execFile('sh', ['-lc', script], {
                        detached: true,
                        stdio: 'ignore',
                    });
                }

                if (child && typeof child.unref === 'function') {
                    child.unref();
                }
                return true;
            } catch (_) {
                return false;
            }
        }

        function quoteForShell(value) {
            return `"${String(value).replace(/(["\\\\$`])/g, '\\\\$1')}"`;
        }

        function getReloadConfig() {
            const config = vscode.workspace.getConfiguration('cgp.autoPatcher');
            const rawMode = String(config.get('reloadMode', 'prompt') || '').toLowerCase();
            const mode = ['prompt', 'auto', 'off'].includes(rawMode) ? rawMode : 'prompt';

            const rawDelay = Number(config.get('reloadDelayMs', 1200));
            const delayMs = Number.isFinite(rawDelay) && rawDelay >= 0
                ? Math.floor(rawDelay)
                : 1200;
            return { mode, delayMs };
        }

        function hasDirtyEditors() {
            try {
                return vscode.workspace.textDocuments.some(doc => doc.isDirty);
            } catch (_) {
                return false;
            }
        }

        function getInstallPaths() {
            const home = os.homedir();
            const installRoot = process.platform === 'win32'
                ? path.join(process.env.LOCALAPPDATA || path.join(home, 'AppData', 'Local'), 'cgp')
                : path.join(home, '.local', 'lib', 'cgp');
            const binDir = process.platform === 'win32'
                ? installRoot
                : path.join(home, '.local', 'bin');
            const exeName = process.platform === 'win32' ? 'cgp.exe' : 'cgp';
            const knownBin = process.platform === 'win32'
                ? path.join(installRoot, exeName)
                : path.join(binDir, exeName);
            return {
                installRoot,
                binDir,
                exeName,
                knownBin,
                versionsDir: path.join(installRoot, 'versions'),
                currentLink: path.join(installRoot, 'current'),
                cacheDir: path.join(installRoot, 'cache'),
                stateFile: path.join(installRoot, 'download_state.json'),
            };
        }

        function readDownloadState(paths) {
            try {
                const raw = fs.readFileSync(paths.stateFile, 'utf8');
                const data = JSON.parse(raw);
                if (data && typeof data === 'object') return data;
            } catch (_) {}
            return { consecutiveFailures: 0 };
        }

        function writeDownloadState(paths, state) {
            try {
                fs.mkdirSync(paths.installRoot, { recursive: true });
                fs.writeFileSync(paths.stateFile, JSON.stringify(state));
            } catch (_) {}
        }

        function pruneCache(cacheDir) {
            let files = [];
            try {
                files = fs.readdirSync(cacheDir);
            } catch (_) {
                return;
            }

            const items = files
                .map((name) => {
                    const full = path.join(cacheDir, name);
                    let stat = null;
                    try { stat = fs.statSync(full); } catch (_) {}
                    if (!stat || !stat.isFile()) return null;
                    if (!(name.endsWith('.tar.gz') || name.endsWith('.zip'))) return null;
                    return { full, mtimeMs: toInt(stat.mtimeMs, 0) };
                })
                .filter(Boolean)
                .sort((a, b) => b.mtimeMs - a.mtimeMs);

            for (let i = MAX_CACHED_ASSETS; i < items.length; i += 1) {
                try { fs.unlinkSync(items[i].full); } catch (_) {}
            }
        }

        function sanitizeTag(tag) {
            return String(tag || '').replace(/[^a-zA-Z0-9._-]/g, '_');
        }

        function toInt(value, fallback) {
            const n = Number(value);
            if (Number.isFinite(n)) return Math.floor(n);
            return fallback;
        }

        // ── helpers ───────────────────────────────────────
        function httpsGet(url, redirects) {
            if (redirects === undefined) redirects = 5;
            return new Promise((resolve, reject) => {
                const opts = {
                    headers: {
                        'User-Agent': 'cgp-auto-patcher',
                        'Accept': 'application/vnd.github+json'
                    },
                    timeout: 10000
                };
                https.get(url, opts, (res) => {
                    if ((res.statusCode === 301 || res.statusCode === 302) && res.headers.location && redirects > 0) {
                        resolve(httpsGet(res.headers.location, redirects - 1));
                        return;
                    }
                    if (res.statusCode < 200 || res.statusCode >= 300) {
                        reject(new Error(`HTTP ${res.statusCode}`));
                        return;
                    }
                    const chunks = [];
                    res.on('data', c => chunks.push(c));
                    res.on('end', () => resolve(Buffer.concat(chunks)));
                    res.on('error', reject);
                }).on('error', reject);
            });
        }

        function which(cmd) {
            return new Promise((resolve) => {
                const shell = process.platform === 'win32' ? 'where' : 'which';
                exec(`${shell} ${cmd}`, { timeout: 5000 }, (err, stdout) => {
                    if (err || !stdout) { resolve(null); return; }
                    const first = stdout.toString().trim().split(/\\r?\\n/)[0];
                    resolve(first || null);
                });
            });
        }

        function selectAsset(plat, arch) {
            const map = {
                'linux-x64':    'cgp-linux-x86_64.tar.gz',
                'linux-arm64':  'cgp-linux-arm64.tar.gz',
                'darwin-x64':   'cgp-macos-x86_64.tar.gz',
                'darwin-arm64': 'cgp-macos-arm64.tar.gz',
                'win32-x64':    'cgp-windows-x86_64.zip',
            };
            return map[`${plat}-${arch}`] || null;
        }

        function execPromise(cmd, opts) {
            return new Promise((resolve, reject) => {
                exec(cmd, opts || {}, (err, stdout, stderr) => {
                    if (err) reject(err);
                    else resolve(stdout);
                });
            });
        }

        module.exports = { activate, deactivate: () => {} };
    """)


def _to_vscode_uri_path(p: Path) -> str:
    """Convert a filesystem path to a VS Code file URI path component.

    Examples:
        /mnt/c/Users/x/.cursor/ext  → /c:/Users/x/.cursor/ext   (WSL)
        C:\\Users\\x\\.cursor\\ext   → /c:/Users/x/.cursor/ext   (Windows)
        /home/x/.cursor/ext          → /home/x/.cursor/ext       (Linux/macOS)
    """
    s = p.as_posix()
    # WSL: /mnt/c/... → /c:/...
    if s.startswith("/mnt/") and len(s) > 6 and s[6] == "/":
        drive = s[5]
        return f"/{drive}:{s[6:]}"
    # Native Windows: C:/... → /c:/...
    if len(s) >= 2 and s[1] == ":":
        return f"/{s[0].lower()}:{s[2:]}"
    return s


def _make_registry_entry(version: str, ext_dir: Path) -> dict:
    """Build an extensions.json entry for our extension."""
    return {
        "identifier": {"id": EXTENSION_ID},
        "version": version,
        "location": {
            "$mid": 1,
            "path": _to_vscode_uri_path(ext_dir),
            "scheme": "file",
        },
        "relativeLocation": _ext_dir_name(version),
        "metadata": {
            "isApplicationScoped": False,
            "isMachineScoped": False,
            "isBuiltin": False,
            "installedTimestamp": int(time.time() * 1000),
            "pinned": True,
            "source": "vsix",
        },
    }


def _read_extensions_json(extensions_root: Path) -> list:
    """Read and parse extensions.json, returning [] on any error."""
    json_path = extensions_root / "extensions.json"
    if not json_path.is_file():
        return []
    try:
        data = json.loads(json_path.read_text(encoding="utf-8"))
        return data if isinstance(data, list) else []
    except (json.JSONDecodeError, OSError):
        return []


def _write_extensions_json(extensions_root: Path, entries: list) -> None:
    """Write entries list to extensions.json."""
    json_path = extensions_root / "extensions.json"
    json_path.write_text(json.dumps(entries), encoding="utf-8")


def _register_extension(extensions_root: Path, version: str, ext_dir: Path) -> None:
    """Add or update the extension entry in extensions.json."""
    entries = _read_extensions_json(extensions_root)
    # Remove any existing cgp-auto-patcher entries
    entries = [
        e for e in entries
        if e.get("identifier", {}).get("id") != EXTENSION_ID
    ]
    entries.append(_make_registry_entry(version, ext_dir))
    _write_extensions_json(extensions_root, entries)


def _unregister_extension(extensions_root: Path) -> None:
    """Remove the extension entry from extensions.json."""
    entries = _read_extensions_json(extensions_root)
    if not entries:
        return
    new_entries = [
        e for e in entries
        if e.get("identifier", {}).get("id") != EXTENSION_ID
    ]
    if len(new_entries) != len(entries):
        _write_extensions_json(extensions_root, new_entries)


def install(
    target: str = "gui",
    *,
    extensions_root: Optional[Path] = None,
    reload_mode: str = DEFAULT_RELOAD_MODE,
    reload_delay_ms: int = DEFAULT_RELOAD_DELAY_MS,
) -> str:
    """Install the auto-patcher extension. Returns a status message."""
    mode = _normalize_reload_mode(reload_mode)
    delay_ms = _normalize_reload_delay_ms(reload_delay_ms)
    root = extensions_root or _extensions_root(target)
    version = __version__

    ext_dir = root / _ext_dir_name(version)

    # Clean up older versions (directories + registry entries)
    for old in _find_existing(root):
        if old != ext_dir:
            shutil.rmtree(old, ignore_errors=True)

    # Create extension directory
    ext_dir.mkdir(parents=True, exist_ok=True)

    # Write package.json
    (ext_dir / "package.json").write_text(
        _generate_package_json(version, reload_mode=mode, reload_delay_ms=delay_ms),
        encoding="utf-8",
    )

    # Write extension.js
    (ext_dir / "extension.js").write_text(_generate_extension_js(), encoding="utf-8")

    # Register in extensions.json so Cursor discovers the extension
    _register_extension(root, version, ext_dir)

    return (
        f"Installed {EXTENSION_NAME} v{version} to {ext_dir} "
        f"(reload_mode={mode}, reload_delay_ms={delay_ms})"
    )


def uninstall(
    target: str = "gui",
    *,
    extensions_root: Optional[Path] = None,
) -> str:
    """Uninstall the auto-patcher extension. Returns a status message."""
    root = extensions_root or _extensions_root(target)

    existing = _find_existing(root)
    if not existing:
        _unregister_extension(root)  # clean up orphan registry entries
        return f"{EXTENSION_NAME} is not installed ({target})"

    for d in existing:
        shutil.rmtree(d, ignore_errors=True)

    _unregister_extension(root)

    return f"Uninstalled {EXTENSION_NAME} from {root}"


def status(
    target: str = "gui",
    *,
    extensions_root: Optional[Path] = None,
) -> str:
    """Check extension installation status. Returns a status message."""
    root = extensions_root or _extensions_root(target)

    existing = _find_existing(root)
    if not existing:
        return f"{EXTENSION_NAME}: not installed ({target})"

    versions = []
    for d in existing:
        # Extract version from directory name
        name = d.name
        ver = name[len(EXTENSION_NAME) + 1:]  # strip "cgp-auto-patcher-"
        versions.append(ver)

    installed_str = ", ".join(versions)
    return f"{EXTENSION_NAME}: installed v{installed_str} ({target}) at {root}"
